---
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "unifi-controller.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{- include "unifi-controller.matchLabels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: https
  {{- end }}
{{- end }}
