---
{{- if and .Values.metrics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "unifi-controller.fullname" . }}
  labels: {{- include "unifi-controller.matchLabels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.metrics.password | b64enc | quote }}
{{- end }}
