---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "unifi-controller.serviceAccountName" . }}
  labels: {{- include "unifi-controller.labels" . | nindent 4 }}
    role: unifi-controller
{{- end }}
...
