apiVersion: v1
appVersion: "1.0"
description: unifi-controller - shut:p
name: unifi-controller
version: 0.1.0
icon: https://bananaspliff.github.io/geek-charts/unifi-controller/logo/unifi-controller.png
