apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
stringData:
  auth.txt: |
    {{- range .Values.mosquitto.users }}
    {{ . }}
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}-metrics
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  username: {{ .Values.metrics.serviceMonitor.username | b64enc }}
  password: {{ .Values.metrics.serviceMonitor.password | b64enc }}