{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled .Values.metrics.serviceMonitor.bearerTokenSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "home-assistant.fullname" . }}-bearer"
  labels: {{- include "home-assistant.labels" . | nindent 4 }}
data:
  bearer_token: {{ .Values.metrics.serviceMonitor.bearerTokenSecret.value | b64enc | quote }}
{{- end }}